# Additon to my docker image for terraria that auto-copies world every six hours to a GCP bucket, and config + world upon exit.
# Also grabs each one from GCP on startup if needed.
#
# GCS Service account with the right permissions needs to be created.
# Add -e GCS_BUCKET=bucket -e GCS_BUCKET_PATH=/terraria to run command. Service account key file looked for is /config/gcs-key.json
#
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0

FROM gitea.findlayis.me/chuck/terraria-docker:latest

RUN \
    apt update && \
    apt install -y cron curl && \
    apt clean

# Install cloud SDK for GCS. This is large unfortunately
# TODO: Find a way to make this far smaller (we only really need gsutil to copy)
RUN \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    apt install apt-transport-https ca-certificates gnupg curl -y && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt update && apt-get install google-cloud-sdk -y

COPY gcp-start.sh /

CMD /gcp-start.sh